project:
  type: website
  output-dir: docs

website:
  title: "Ross EcoAnalytics"
  favicon: favicon-16x16.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Services"
        href: services.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

